version: 2
updates:
  - package-ecosystem: gomod
    directory: "/"
    target-branch: release-1.32
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "*"
        update-types: 
          - "version-update:semver-major"
          - "version-update:semver-minor"

  - package-ecosystem: gomod
    directory: "/"
    target-branch: release-1.31
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "*"
        update-types: 
          - "version-update:semver-major"
          - "version-update:semver-minor"

  - package-ecosystem: gomod
    directory: "/"
    target-branch: release-1.30
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "*"
        update-types: 
          - "version-update:semver-major"
          - "version-update:semver-minor"

  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10

  - package-ecosystem: "bundler"
    directory: "cloud-build"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10

