version: 2
updates:
  - package-ecosystem: gomod
    directory: "/"
    target-branch: release-1.27
    schedule:
      interval: weekly
    open-pull-requests-limit: 10

  - package-ecosystem: gomod
    directory: "/"
    target-branch: release-1.26
    schedule:
      interval: weekly
    open-pull-requests-limit: 10

  - package-ecosystem: gomod
    directory: "/"
    target-branch: release-1.25
    schedule:
      interval: weekly
    open-pull-requests-limit: 10

  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10

  - package-ecosystem: "bundler"
    directory: "cloud-build"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10

