=begin
#Kubernetes

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: v1.17.1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.2.3-SNAPSHOT

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Kubernetes::IoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceDefinitionSpec
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'IoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceDefinitionSpec' do
  before do
    # run before each test
    @instance = Kubernetes::IoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceDefinitionSpec.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of IoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceDefinitionSpec' do
    it 'should create an instance of IoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceDefinitionSpec' do
      expect(@instance).to be_instance_of(Kubernetes::IoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceDefinitionSpec)
    end
  end
  describe 'test attribute "conversion"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "group"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "names"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "preserve_unknown_fields"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "scope"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "versions"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
