=begin
#Kubernetes

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: v1.17.1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.2.3-SNAPSHOT

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Kubernetes::OrgProjectcalicoCrdV1BGPConfigurationListMetadata
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'OrgProjectcalicoCrdV1BGPConfigurationListMetadata' do
  before do
    # run before each test
    @instance = Kubernetes::OrgProjectcalicoCrdV1BGPConfigurationListMetadata.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of OrgProjectcalicoCrdV1BGPConfigurationListMetadata' do
    it 'should create an instance of OrgProjectcalicoCrdV1BGPConfigurationListMetadata' do
      expect(@instance).to be_instance_of(Kubernetes::OrgProjectcalicoCrdV1BGPConfigurationListMetadata)
    end
  end
  describe 'test attribute "continue"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "remaining_item_count"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "resource_version"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "self_link"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
