=begin
#Kubernetes

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: v1.17.1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.2.3-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for Kubernetes::AuthorizationV1Api
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'AuthorizationV1Api' do
  before do
    # run before each test
    @api_instance = Kubernetes::AuthorizationV1Api.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AuthorizationV1Api' do
    it 'should create an instance of AuthorizationV1Api' do
      expect(@api_instance).to be_instance_of(Kubernetes::AuthorizationV1Api)
    end
  end

  # unit tests for create_authorization_v1_namespaced_local_subject_access_review
  # create a LocalSubjectAccessReview
  # @param namespace object name and auth scope, such as for teams and projects
  # @param body 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :dry_run When present, indicates that modifications should not be persisted. An invalid or unrecognized dryRun directive will result in an error response and no further processing of the request. Valid values are: - All: all dry run stages will be processed
  # @option opts [String] :field_manager fieldManager is a name associated with the actor or entity that is making these changes. The value must be less than or 128 characters long, and only contain printable characters, as defined by https://golang.org/pkg/unicode/#IsPrint.
  # @option opts [String] :pretty If &#39;true&#39;, then the output is pretty printed.
  # @return [IoK8sApiAuthorizationV1LocalSubjectAccessReview]
  describe 'create_authorization_v1_namespaced_local_subject_access_review test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for create_authorization_v1_self_subject_access_review
  # create a SelfSubjectAccessReview
  # @param body 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :dry_run When present, indicates that modifications should not be persisted. An invalid or unrecognized dryRun directive will result in an error response and no further processing of the request. Valid values are: - All: all dry run stages will be processed
  # @option opts [String] :field_manager fieldManager is a name associated with the actor or entity that is making these changes. The value must be less than or 128 characters long, and only contain printable characters, as defined by https://golang.org/pkg/unicode/#IsPrint.
  # @option opts [String] :pretty If &#39;true&#39;, then the output is pretty printed.
  # @return [IoK8sApiAuthorizationV1SelfSubjectAccessReview]
  describe 'create_authorization_v1_self_subject_access_review test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for create_authorization_v1_self_subject_rules_review
  # create a SelfSubjectRulesReview
  # @param body 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :dry_run When present, indicates that modifications should not be persisted. An invalid or unrecognized dryRun directive will result in an error response and no further processing of the request. Valid values are: - All: all dry run stages will be processed
  # @option opts [String] :field_manager fieldManager is a name associated with the actor or entity that is making these changes. The value must be less than or 128 characters long, and only contain printable characters, as defined by https://golang.org/pkg/unicode/#IsPrint.
  # @option opts [String] :pretty If &#39;true&#39;, then the output is pretty printed.
  # @return [IoK8sApiAuthorizationV1SelfSubjectRulesReview]
  describe 'create_authorization_v1_self_subject_rules_review test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for create_authorization_v1_subject_access_review
  # create a SubjectAccessReview
  # @param body 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :dry_run When present, indicates that modifications should not be persisted. An invalid or unrecognized dryRun directive will result in an error response and no further processing of the request. Valid values are: - All: all dry run stages will be processed
  # @option opts [String] :field_manager fieldManager is a name associated with the actor or entity that is making these changes. The value must be less than or 128 characters long, and only contain printable characters, as defined by https://golang.org/pkg/unicode/#IsPrint.
  # @option opts [String] :pretty If &#39;true&#39;, then the output is pretty printed.
  # @return [IoK8sApiAuthorizationV1SubjectAccessReview]
  describe 'create_authorization_v1_subject_access_review test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_authorization_v1_api_resources
  # get available resources
  # @param [Hash] opts the optional parameters
  # @return [IoK8sApimachineryPkgApisMetaV1APIResourceList]
  describe 'get_authorization_v1_api_resources test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
