=begin
#Kubernetes

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: v1.17.1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.2.3-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for Kubernetes::AuthenticationV1Api
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'AuthenticationV1Api' do
  before do
    # run before each test
    @api_instance = Kubernetes::AuthenticationV1Api.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AuthenticationV1Api' do
    it 'should create an instance of AuthenticationV1Api' do
      expect(@api_instance).to be_instance_of(Kubernetes::AuthenticationV1Api)
    end
  end

  # unit tests for create_authentication_v1_token_review
  # create a TokenReview
  # @param body 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :dry_run When present, indicates that modifications should not be persisted. An invalid or unrecognized dryRun directive will result in an error response and no further processing of the request. Valid values are: - All: all dry run stages will be processed
  # @option opts [String] :field_manager fieldManager is a name associated with the actor or entity that is making these changes. The value must be less than or 128 characters long, and only contain printable characters, as defined by https://golang.org/pkg/unicode/#IsPrint.
  # @option opts [String] :pretty If &#39;true&#39;, then the output is pretty printed.
  # @return [IoK8sApiAuthenticationV1TokenReview]
  describe 'create_authentication_v1_token_review test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_authentication_v1_api_resources
  # get available resources
  # @param [Hash] opts the optional parameters
  # @return [IoK8sApimachineryPkgApisMetaV1APIResourceList]
  describe 'get_authentication_v1_api_resources test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
