name: 'Build and Push Cloud Controller Image'
on:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - 
        name: Set up Docker Metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            cr.brightbox.com/${{ vars.CR_ACCOUNT }}/${{ vars.CR_REPO }}/brightbox-cloud-controller-manager
          tags: |
            type=semver,pattern={{version}}
      - 
        name: Login to Brightbox Container Registry
        uses: docker/login-action@v2
        with:
          registry: cr.brightbox.com
          username: ${{ vars.CR_USERNAME }}
          password: ${{ secrets.CR_SECRET }}
      - 
        name: Docker build and push
        uses: docker/build-push-action@v4
        with:
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
